### ISSUE TITLE
How to complie to css

### ISSUE THREAD

**Issue by ghost** [rriepe/1pxdeep#18]
`lessc 1pxdeep.less 1pxdeep.css`

> NameError: variable @color1a is undefined in 1pxdeep.less on line 25, column 37:
> 24
> 25 @modal-backdrop-bg:                 @color1a;
> 26

Get this error while complie.
`lessc scheme.less scheme.css`
But the scheme.css is blank!

**Comment by felixvictor** [comment]
From the documentation

> Include scheme.less anywhere.
> Include 1pxdeep.less after all Bootstrap LESS.
